### ISSUE TITLE
warning C4996: 'GetVersionExA': was declared deprecated

### ISSUE THREAD

**Issue by sepehr-laal** [Downstream/ds_cinder#3]
While compiling `platform.vcxproj`under VS2013, I am getting: `warning C4996: 'GetVersionExA': was declared deprecated`

I looked it up, http://stackoverflow.com/questions/20031597/error-c4996-received-when-compiling-sqlite-c-in-visual-studio-2013 seems like a possible fix.

**Comment by gordeaoux** [comment]
Closing this as "won't fix"

**Comment by DXGLdotinfo** [comment]
This will make it gone:
`#pragma warning(disable: 4996)`
